// ─── ATELIER — Brutalist Minimalist Design System ─────────────────────────
export const tokens = {
  black:    '#000000',
  white:    '#FFFFFF',
  offwhite: '#F5F5F5',
  gray100:  '#F0F0F0',
  gray200:  '#E0E0E0',
  gray400:  '#AAAAAA',
  gray600:  '#666666',
  gray800:  '#333333',
};

export const font = "'Helvetica Neue', 'Arial Narrow', Arial, sans-serif";

const styles = {
  nav: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0 24px',
    height: '48px',
    backgroundColor: tokens.white,
    borderBottom: `1px solid ${tokens.gray200}`,
    position: 'sticky',
    top: 0,
    zIndex: 1000,
  },
  logo: {
    fontFamily: font,
    fontSize: '13px',
    letterSpacing: '0.5px',
    fontWeight: 700,
    margin: 0,
    color: tokens.black,
    cursor: 'pointer',
    textTransform: 'uppercase',
  },
  container: { maxWidth: '1440px', margin: '0 auto', padding: '0 24px' },
  btnBlack: {
    backgroundColor: tokens.black,
    color: tokens.white,
    border: 'none',
    padding: '0 32px',
    height: '44px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    cursor: 'pointer',
    fontSize: '11px',
    fontFamily: font,
    fontWeight: 500,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 0,
  },
  btnWhite: {
    backgroundColor: tokens.white,
    color: tokens.black,
    border: `1px solid ${tokens.black}`,
    padding: '0 32px',
    height: '44px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    cursor: 'pointer',
    fontSize: '11px',
    fontFamily: font,
    fontWeight: 500,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 0,
  },
  input: {
    width: '100%',
    padding: '0',
    height: '44px',
    marginBottom: '16px',
    border: 'none',
    borderBottom: `1px solid ${tokens.gray200}`,
    outline: 'none',
    fontSize: '13px',
    backgroundColor: 'transparent',
    fontFamily: font,
    color: tokens.black,
    boxSizing: 'border-box',
    letterSpacing: '0.3px',
    borderRadius: 0,
    WebkitAppearance: 'none',
  },
  cartDrawer: {
    position: 'fixed',
    top: 0,
    right: 0,
    width: '480px',
    height: '100%',
    backgroundColor: tokens.white,
    color: tokens.black,
    borderLeft: `1px solid ${tokens.gray200}`,
    zIndex: 1500,
    padding: '0',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: font,
  },
};

export default styles;
